// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZjiSH8z3NbsI52MJNaVNoH1Dvw0Sk4Y',
    appId: '1:479779854595:web:03a256a0c5551d43717136',
    messagingSenderId: '479779854595',
    projectId: 'mechanic-online-8b01b',
    authDomain: 'mechanic-online-8b01b.firebaseapp.com',
    storageBucket: 'mechanic-online-8b01b.appspot.com',
    measurementId: 'G-T14EJ5EKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfm3f8uQNtATrg0bPaMpkj3jiOysN6NZw',
    appId: '1:479779854595:android:91f5b9e81495639c717136',
    messagingSenderId: '479779854595',
    projectId: 'mechanic-online-8b01b',
    storageBucket: 'mechanic-online-8b01b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz9PSPxnH6FN0V8qRvyClZ2D-0xLvk73E',
    appId: '1:479779854595:ios:a87457a1f1bef096717136',
    messagingSenderId: '479779854595',
    projectId: 'mechanic-online-8b01b',
    storageBucket: 'mechanic-online-8b01b.appspot.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz9PSPxnH6FN0V8qRvyClZ2D-0xLvk73E',
    appId: '1:479779854595:ios:2b93b99b88b361de717136',
    messagingSenderId: '479779854595',
    projectId: 'mechanic-online-8b01b',
    storageBucket: 'mechanic-online-8b01b.appspot.com',
    iosBundleId: 'com.example.projects.RunnerTests',
  );
}
